### ISSUE TITLE
Missing page curd controller when opening Pages in admin menu

### ISSUE THREAD

**Issue by dmgdwd** [Laravel-Backpack/PageManager#44]
I've looked through the issues and read the issues concerning pages. But nothing seems to work.  I think I may have missed a step.
I have-
 * cloned demo
 * composer install
 * composer update

But I still get this error message in log.  Any help would be greatly appreciated. 
Thanks

`2017-06-26 15:55:02] local.ERROR: ReflectionException: Class Backpack\PageManager\App\Http\Controllers\Admin\PageCrudController does not exist in /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('Backpack\\PageMa...')
#1 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('Backpack\\PageMa...')
#2 /var/www/site/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('Backpack\\PageMa...')
#3 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('Backpack\\PageMa...')
#4 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(217): Illuminate\Foundation\Application->make('Backpack\\PageMa...')
#5 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(747): Illuminate\Routing\Route->getController()
#6 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Route.php(708): Illuminate\Routing\Route->controllerMiddleware()
#7 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(587): Illuminate\Routing\Route->gatherMiddleware()
#8 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(567): Illuminate\Routing\Router->gatherRouteMiddleware(Object(Illuminate\Routing\Route))
#9 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#10 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/site/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/site/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /var/www/site/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main}  
`

**Comment by dmgdwd** [comment]
Sorry I just read the PageManager readme
I ran the php artisan vendor:publish command and all works
